# Generated by Django 4.2.1 on 2023-09-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epokabootcamp', '0002_student_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
